# Generated by Django 4.2.7 on 2023-12-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IHA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_ismi', models.CharField(max_length=150)),
                ('ulke', models.CharField(max_length=150)),
                ('telefon_no', models.CharField(max_length=11, unique=True)),
                ('adres', models.TextField(max_length=250)),
                ('kayit_tarihi', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kiralama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiralama_tarihi', models.DateField()),
                ('kiralama_suresi', models.IntegerField()),
                ('kiralama_ucreti', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IHA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IHA.iha')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IHA.musteri')),
            ],
        ),
    ]
