# Generated by Django 4.2.7 on 2023-12-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IHA', '0003_kiralama_kiralama_saati_alter_musteri_telefon_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iha',
            name='aktif',
        ),
        migrations.AddField(
            model_name='musteri',
            name='kiralanmis_IHAlar',
            field=models.ManyToManyField(through='IHA.Kiralama', to='IHA.iha'),
        ),
    ]
